---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

inputs:
  - name: pcfdemo-ci

run:
  path: pcfdemo/ci/tasks/integration.sh
  args: [
    --input-dir, pcfdemo
  ]
